/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

/**
 * Autogenerated input type of AddStar
 */
export interface AddStarInput {
  starrableId: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of RemoveStar
 */
export interface RemoveStarInput {
  starrableId: string;
  clientMutationId?: string | null;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
